service: trash-ai-serverless-backend
frameworkVersion: '2 || 3'

custom:
  prefix: trash-ai

  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localstack # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000


provider:
  name: aws
  region: ${opt:region}
  runtime: nodejs14.x
  role: ${ssm:/${self:custom.prefix}/role_arn}
  environment:
    main_bucket: ${ssm:/${self:custom.prefix}/${opt:region}/main_bucket_name}
  httpApi:
    cors: true

  lambdaHashingVersion: '20201221'


functions:
  api:
    handler: handler.handler

    events:
      - httpApi: '*'

plugins:
  - serverless-localstack
  - serverless-offline
